### ISSUE TITLE
Exception if delete event without throwing to trash

### ISSUE THREAD

**Issue by bear0330** [treeio/treeio#160]
When I delete a event I got this:

```
Traceback (most recent call last):

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/core/handlers/base.py", line 121, in get_response
    response = middleware_method(request, e)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/nuwa/webapps/bm_nuwa/Source/Project/BusinessManagement/Nuwa/treeio/core/decorators.py", line 48, in wrap
    return f(request, *args, **kwargs)

  File "/home/nuwa/webapps/bm_nuwa/Source/Project/BusinessManagement/Nuwa/treeio/core/decorators.py", line 124, in wrap
    response = f(request, *args, **kwargs)

  File "/home/nuwa/webapps/bm_nuwa/Source/Project/BusinessManagement/Nuwa/treeio/events/views.py", line 345, in event_delete
    event.delete()

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/models/base.py", line 674, in delete
    collector.delete()

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/models/deletion.py", line 62, in decorated
    func(self, *args, **kwargs)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/models/deletion.py", line 316, in delete
    query.delete_batch(pk_list, self.using)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/models/sql/subqueries.py", line 48, in delete_batch
    self.do_query(self.model._meta.db_table, where, using=using)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/models/sql/subqueries.py", line 33, in do_query
    self.get_compiler(using).execute_sql(None)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/johnny/cache.py", line 387, in newfun
    ret = original(cls, *args, **kwargs)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/johnny/cache.py", line 332, in newfun
    return original(cls, *args, **kwargs)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 122, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)

  File "/home/nuwa/webapps/bm_nuwa/lib/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue

IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`nuwa_bm_nuwa`.`core_updaterecord_about`, CONSTRAINT `object_id_refs_id_863082d8` FOREIGN KEY (`object_id`) REFERENCES `core_object` (`id`))')
```

**Comment by tovmeod** [comment]
I will try to add a test case to reproduce this locally, can you post here what the object you tried to delete had? I'm not interested in the content but which fields were filled.
